/**
 * FILE: app/api/system-setup-wizard/generate-passphrase/route.js
 * ROLE: Wizard-session only (Step 8 of app/system-setup-wizard) — no
 *       account, no role. Gated by isSetupWizardLocked() AND
 *       hasWizardSession(), same double-gate pattern as every other
 *       route under app/api/system-setup-wizard/.
 *
 * PURPOSE:
 * Generates the vault passphrase that, together with Step 4's owner
 * AdminProfile, is what actually flips isSetupWizardLocked() to true
 * (services/setupWizardStatus.js) — this is the last step that
 * changes any state; Step 9 only verifies, Step 10 only confirms.
 *
 * Reuses generateAndDistributePassphrase() directly from
 * app/api/system-vault-setup/route.js (now exported for this reason)
 * instead of duplicating the rotate + email + R2-save + audit-log
 * flow a third time. Deliberately does NOT call that route over HTTP
 * with the x-vault-setup-key header — VAULT_SETUP_KEY and
 * WIZARD_SETUP_KEY are two separate trust boundaries by design (see
 * api-setup-guide.txt's vaultSecurity group), and the wizard's own
 * WIZARD_SETUP_KEY session (already verified back in Step 1) is the
 * correct boundary for this first-run bootstrap case — there is no
 * admin session yet to hold a VAULT_SETUP_KEY-gated request to.
 *
 * Since this route only ever runs before setup completes, the target
 * table is realistically always empty (isSetupWizardLocked() would
 * already have 404'd this whole route otherwise) — but the same
 * hasDbPassphrase/hasEnvFallback check GET uses is still run first so
 * a page refresh after a successful generation reports the existing
 * status instead of silently trying (and failing, by design) to
 * generate a second one.
 *
 * DATA FLOW:
 * 1. isSetupWizardLocked() -> setup already done -> reject
 * 2. hasWizardSession() -> Step 1 not passed this session -> reject
 * 3. Check VaultPassphrase / VAULT_PASSPHRASE_HASH — already set?
 *    -> return isConfigured status only, no plaintext, no regenerate
 * 4. Nothing set yet -> generateAndDistributePassphrase() -> return
 *    the plaintext ONCE, plus email/R2 outcome flags
 * 5. logSecurityEvent({ eventType: "setup_passphrase_generated" }) —
 *    on top of generateAndDistributePassphrase()'s own internal
 *    "vault_passphrase_set" audit entry, so this specific wizard
 *    milestone is distinguishable in the Security Logs page from a
 *    later manual rotation through the real vault-setup page
 * 6. logSecurityEvent({ eventType: "setup_completed" }) — see the
 *    SELF-LOCK NOTE below for why this fires HERE, not in a later
 *    Step 10 route.
 *
 * SELF-LOCK NOTE (important):
 * isSetupWizardLocked() returns true once BOTH an owner AdminProfile
 * AND a set VaultPassphrase exist. Step 4 (earlier in this same
 * session) already guarantees the owner exists, so the instant this
 * route's generateAndDistributePassphrase() call succeeds, the wizard
 * is ALREADY locked — every route under app/api/system-setup-wizard/,
 * including this one on a second call, starts with the exact same
 * isSetupWizardLocked() check and would 404 immediately after. A
 * separate "Step 10: mark complete" API call would therefore always
 * fail with "Setup has already been completed" the moment it tried to
 * run. So setup_completed is logged HERE, in the same request that
 * actually causes the lock to engage, instead of in a route that
 * could never successfully fire afterward. Step 9 (Verify Vault
 * Access) and Step 10 (Done) are UI-only from this point on — a plain
 * link to the vault and a plain "you're done" screen, no further
 * wizard API calls, by design.
 */
export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { prisma } from "@/services/prisma";
import { isSetupWizardLocked } from "@/services/setupWizardStatus";
import { hasWizardSession } from "@/services/wizardSession";
import { logSecurityEvent } from "@/services/securityLog";
import { generateAndDistributePassphrase } from "@/app/api/system-vault-setup/route";

export async function GET(request) {
  if (await isSetupWizardLocked()) {
    return NextResponse.json(
      { success: false, data: null, message: "Setup has already been completed." },
      { status: 404 }
    );
  }

  if (!hasWizardSession(request)) {
    return NextResponse.json(
      { success: false, data: null, message: "Setup key required." },
      { status: 401 }
    );
  }

  try {
    const vaultPassphraseRow = await prisma.vaultPassphrase.findUnique({
      where: { id: "vault_passphrase" },
      select: { passphraseHash: true },
    });
    const hasDbPassphrase = Boolean(vaultPassphraseRow?.passphraseHash);
    const hasEnvFallback = Boolean(process.env.VAULT_PASSPHRASE_HASH);

    if (hasDbPassphrase || hasEnvFallback) {
      return NextResponse.json({
        success: true,
        data: { isConfigured: true, autoGenerated: false },
        message: "A vault passphrase is already set. It can't be shown again — check your email or Google Drive backup from when it was generated.",
      });
    }

    const result = await generateAndDistributePassphrase({
      actor: "wizard-setup",
      reason: "Setup wizard: first-run vault passphrase generation",
      request,
      generatedByLabel: "setup wizard (first-run)",
    });

    await logSecurityEvent({
      eventType: "setup_passphrase_generated",
      actor: "wizard-setup",
      request,
      details: `Setup wizard: vault passphrase generated. Email sent: ${result.emailSent}. Saved to R2: ${result.r2Saved}.`,
    });

    // This save is the exact action that flips isSetupWizardLocked()
    // to true (owner AdminProfile from Step 4 + this VaultPassphrase
    // together satisfy it) — log setup_completed now, in the same
    // request, because no later wizard route could ever fire it
    // successfully once the lock engages. See SELF-LOCK NOTE above.
    await logSecurityEvent({
      eventType: "setup_completed",
      actor: "wizard-setup",
      request,
      details: "Setup wizard: first-run setup complete (owner admin + vault passphrase both now set).",
    });

    return NextResponse.json({
      success: true,
      data: { isConfigured: true, autoGenerated: true, ...result },
      message: "Vault passphrase generated. Copy it now — it will not be shown again.",
    });
  } catch (error) {
    console.error("[api/system-setup-wizard/generate-passphrase] Failed:", error.message);
    return NextResponse.json(
      { success: false, data: null, message: "We couldn't generate the vault passphrase. Please try again." },
      { status: 500 }
    );
  }
}
