/**
 * FILE: services/vaultPassphraseBackup.js
 * PURPOSE:
 * Single shared implementation of "save the freshly-rotated vault
 * passphrase to Google Drive as a .txt file" — previously this exact
 * block (build file content, upload, catch-and-log) was copy-pasted
 * in three places (services/breachResponse.js, the auto-rotate cron
 * route, and the manual system-vault-setup route), so a fix or
 * improvement made in one never reached the other two.
 *
 * WHY THIS FILE EXISTS (Task 4):
 * The owner observed passphrases rotating (email received) with no
 * matching file showing up in Google Drive. Every existing call site
 * already attempted the Drive upload, but a single transient failure
 * (an expired OAuth access token, a momentary network blip, Drive
 * rate-limiting) was caught, logged to the server console, and then
 * silently dropped — nothing ever tried again, and nothing surfaced
 * that failure anywhere the owner could see it. This helper fixes
 * that by:
 *   1. Retrying the upload once (a few seconds apart) before giving up,
 *      since most Drive failures are transient rather than permanent.
 *   2. Always returning a clear driveSaved boolean the caller can log,
 *      so a persistent failure is at least visible in SecurityLog
 *      (existing "Saved to Drive: <bool>" detail lines already surface
 *      this — they just needed the retry behind them to make the
 *      false case rarer).
 *
 * Email and Drive remain independent — a Drive failure here must never
 * stop the plaintext email from having already been sent by the caller.
 */
import { uploadToDrive } from "@/services/googleDrive";
import { getVaultRecoveryUrl } from "@/services/vaultAuth";

const RETRY_DELAY_MS = 3000;

function buildPassphraseFileContents({ newPassphrase, generatedByLabel, generatedAt, vaultRecoveryUrl }) {
  return (
    `Villa Azure Resort — Vault Recovery Passphrase\n` +
    `Generated: ${generatedAt}\n` +
    `Generated by: ${generatedByLabel}\n\n` +
    `Passphrase:\n${newPassphrase}\n\n` +
    `This passphrase gates the disaster-recovery page at [${vaultRecoveryUrl.replace(/^https?:\/\//, "")}](${vaultRecoveryUrl}).\n` +
    `This was generated automatically — the previous passphrase no longer works.\n` +
    `Keep this file private — do not share it outside the resort owner.\n`
  );
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * saveVaultPassphraseToDrive
 * Builds the standard passphrase backup .txt and uploads it to the
 * configured Google Drive folder, retrying once on failure before
 * giving up. Never throws — a permanent failure returns
 * { driveSaved: false, driveViewLink: null } so the caller can log it
 * and continue (rotation + email must never be undone by this step).
 *
 * @param {string} newPassphrase   - plaintext passphrase, same value emailed to the owner
 * @param {string} generatedByLabel - e.g. "Gatekeeper 1 — Login brute force: ..." or "Automatic 30-day rotation"
 * @returns {Promise<{ driveSaved: boolean, driveViewLink: string|null }>}
 */
export async function saveVaultPassphraseToDrive({ newPassphrase, generatedByLabel }) {
  const generatedAt = new Date().toISOString();
  const vaultRecoveryUrl = await getVaultRecoveryUrl();
  const fileContents = buildPassphraseFileContents({
    newPassphrase,
    generatedByLabel,
    generatedAt,
    vaultRecoveryUrl,
  });
  const fileName = `vault-passphrase-${generatedAt.replace(/[:.]/g, "-")}.txt`;
  const buffer = Buffer.from(fileContents, "utf-8");

  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const result = await uploadToDrive(fileName, buffer, "text/plain");
      return { driveSaved: true, driveViewLink: result.viewLink };
    } catch (error) {
      const isFinalAttempt = attempt === 2;
      console.error(
        `[vaultPassphraseBackup] Drive upload attempt ${attempt}/2 failed:`,
        error.message,
        isFinalAttempt ? "— giving up, email copy is the only record." : "— retrying once more."
      );
      if (!isFinalAttempt) await sleep(RETRY_DELAY_MS);
    }
  }

  return { driveSaved: false, driveViewLink: null };
}
