/**
 * FILE: app/system-setup-wizard/VaultPassphraseStep.jsx
 * ROLE: Client Component — Step 7 of the setup wizard
 *
 * PURPOSE:
 * Renders once ExternalSetupStep's "Continue" is clicked (Step 6).
 * Single explicit-click button — never fires on mount, since this has
 * two real side effects (an email to VAULT_OWNER_EMAIL, a .txt save
 * to Cloudflare R2) and, unlike Step 6's checks, an irreversible one:
 * generating the passphrase is the action that completes first-run
 * setup and locks the whole wizard (see the API route's own
 * SELF-LOCK NOTE for why).
 *
 * The plaintext is shown exactly once, straight from the response —
 * never re-fetchable, never re-shown on refresh. Copy it now or find
 * it later via the email/R2 backup, same rule the real vault-setup
 * page already enforces.
 *
 * DATA FLOW:
 * 1. "Generate Vault Passphrase" click -> GET
 *    /api/system-setup-wizard/generate-passphrase
 * 2. Response includes the plaintext exactly once (autoGenerated:
 *    true) — held only in local state, never written anywhere else
 *    client-side. It also includes vaultUrl (the current, hash-derived
 *    recovery page link) on every branch, since neither Step 8 nor
 *    Step 10 can ever call a wizard API route themselves once this
 *    request's success locks the whole wizard.
 * 3. Once generated, this session is effectively complete server-side
 *    — Continue hands off to <VerifyVaultAccessStep vaultUrl={...} />
 *    (Step 8), which is UI-only from here (no further wizard API
 *    calls — see the route's SELF-LOCK NOTE)
 */
"use client";

import { useState } from "react";
import { useToast } from "./shared/useToast";
import ToastStack from "./shared/ToastStack";
import VerifyVaultAccessStep from "./VerifyVaultAccessStep";

export default function VaultPassphraseStep() {
  const { toasts, showToast, dismissToast } = useToast();

  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [loadError, setLoadError] = useState(null);

  async function handleGenerate() {
    setIsGenerating(true);
    setLoadError(null);
    try {
      const response = await fetch("/api/system-setup-wizard/generate-passphrase");
      const apiResult = await response.json();

      if (!response.ok || !apiResult.success) {
        setLoadError(apiResult.message ?? "We couldn't generate the vault passphrase. Please try again.");
        return;
      }
      setResult(apiResult.data);
      if (apiResult.data.autoGenerated) {
        showToast("✓ Vault passphrase generated.", "success");
      }
    } catch {
      setLoadError("We couldn't reach the server. Check your connection and try again.");
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(result.passphrase);
      showToast("✓ Passphrase copied.", "success");
    } catch {
      showToast("✕ Couldn't copy automatically — please copy it manually.", "error");
    }
  }

  return (
    <div className="setupWizardStepGroup">
      <ToastStack toasts={toasts} onDismiss={dismissToast} />

      <div className="setupWizardCard">
        <span className="setupWizardEyebrow">Step 7 of 10</span>
        <h1 className="setupWizardTitle">Generate the vault passphrase</h1>
        <p className="setupWizardBody">
          This creates the disaster-recovery passphrase for the owner
          vault, emails it to <code>VAULT_OWNER_EMAIL</code>, and saves
          a backup copy to Cloudflare R2. It also completes first-run
          setup — after this, the wizard page and every route under it
          will stop responding, even if you still have this session
          open.
        </p>

        {loadError && <p className="setupWizardError">{loadError}</p>}

        {!result && (
          <button
            type="button"
            className="setupWizardButton"
            onClick={handleGenerate}
            disabled={isGenerating}
          >
            {isGenerating ? "Generating…" : "Generate Vault Passphrase"}
          </button>
        )}

        {result && !result.autoGenerated && (
          <p className="setupWizardBody">{`A vault passphrase is already set. It can't be shown again here — check your email or R2 backup from when it was generated.`}</p>
        )}

        {result?.autoGenerated && (
          <>
            <div className="setupWizardCommandRow">
              <code className="setupWizardCodeBlock">{result.passphrase}</code>
              <button type="button" className="setupWizardCopyButton" onClick={handleCopy}>
                Copy
              </button>
            </div>
            <p className="setupWizardError">
              Copy this now — it will not be shown again. Emailed:{" "}
              {result.emailSent ? "yes" : "no, check server logs"}. Saved
              to R2: {result.r2Saved ? "yes" : "no, check server logs"}.
            </p>
          </>
        )}
      </div>

      {result?.isConfigured && <VerifyVaultAccessStep vaultUrl={result.vaultUrl} />}
    </div>
  );
}
