/**
 * FILE: scripts/setupVault.js
 * PURPOSE:
 * One-time local setup for the owner vault. Run this ONCE on your own
 * machine — never deploy this as an API route, since it's the only
 * place the TOTP secret is ever generated in plaintext.
 *
 * USAGE:
 *   node scripts/setupVault.js
 *     → auto-generates a cryptographically random passphrase and prints
 *       it once to the terminal. Save it immediately — it is never
 *       stored or shown again.
 *   node scripts/setupVault.js "your-chosen-passphrase-min-12-chars"
 *     → uses your own passphrase instead of generating one.
 *
 * OUTPUT:
 *   Creates the OwnerVault row, then writes owner-vault-passphrase.txt
 *   to the project root as a local recovery copy of the plaintext
 *   passphrase (see buildPassphraseFileContents below) — read it once,
 *   store it somewhere safe, then delete it from disk — never commit
 *   it. Prints a confirmation (row id + passphrase hash) after saving
 *   so you can verify the row actually landed in the database.
 *
 * QR CODE — DELIBERATELY REMOVED FOR NOW:
 *   This script no longer generates a TOTP QR code or backs one up to
 *   Cloudflare R2. QR generation is only meaningful once this project
 *   is deployed behind a real, final custom domain (the otpauth:// URI
 *   embedded in the QR is tied to that identity) — generating one
 *   against a local/placeholder setup would just mean re-doing this
 *   step later anyway. The raw TOTP secret is printed to the terminal
 *   instead, for manual entry into an authenticator app in the
 *   meantime. Re-add QR generation (services/totp.js's
 *   generateTotpQrCode, still intact and unused for now) once the
 *   deploy step has a custom domain finalized.
 */
import "./loadEnv.mjs";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import fs from "fs";
import { prisma } from "../services/prisma.js";
import { generateTotpSecret } from "../services/totp.js";

/**
 * generatePassphrase
 * Creates a cryptographically random, URL-safe passphrase of at least
 * 12 characters (default 24) using Node's crypto module — never Math.random().
 */
function generatePassphrase(length = 24) {
  return crypto.randomBytes(length).toString("base64url").slice(0, length);
}

/**
 * buildPassphraseFileContents
 * Same structure as services/vaultPassphraseBackup.js's file format,
 * adapted for the Owner Vault's own passphrase (a separate system from
 * the hidden recovery page — see prisma/schema.prisma's OwnerVault vs
 * VaultPassphrase models). Kept local-only for now — this is the
 * initial setup run, so there's no email/R2 rotation flow to mirror.
 */
function buildPassphraseFileContents({ passphrase, generatedAt }) {
  return (
    `your-private-resort — Owner Vault Recovery Passphrase\n` +
    `Generated: ${generatedAt}\n` +
    `Generated by: Generated from the setup wizard, step 6\n\n` +
    `Passphrase:\n${passphrase}\n\n` +
    `This passphrase (together with your authenticator app code) gates the Owner Vault dashboard login (POST /api/vault/login).\n` +
    `This is the initial vault passphrase — save it now, it will not be shown again after this run.\n` +
    `Keep this file private — do not share it outside the resort owner.\n`
  );
}

async function main() {
  let passphrase = process.argv[2];
  let wasGenerated = false;

  // No passphrase provided — auto-generate a secure one instead of failing.
  if (!passphrase) {
    passphrase = generatePassphrase();
    wasGenerated = true;
  }

  if (passphrase.length < 12) {
    console.error("Provide a passphrase of at least 12 characters as the first argument.");
    process.exit(1);
  }

  // Refuse to run if a vault already exists — prevents accidentally
  // wiping out the owner's existing TOTP pairing.
  const existing = await prisma.ownerVault.findFirst();
  if (existing) {
    console.error("A vault already exists. Delete the OwnerVault row manually first if you intend to reset.");
    process.exit(1);
  }

  const passphraseHash = await bcrypt.hash(passphrase, 12);
  const totpSecret = generateTotpSecret();

  const createdVault = await prisma.ownerVault.create({ data: { passphraseHash, totpSecret } });

  // Save a local recovery copy of the plaintext passphrase — see
  // buildPassphraseFileContents above. Local-only for now, same as the
  // TOTP secret below — nothing here is uploaded anywhere.
  const generatedAt = new Date().toISOString();
  const passphraseFileContents = buildPassphraseFileContents({ passphrase, generatedAt });
  fs.writeFileSync("owner-vault-passphrase.txt", passphraseFileContents);

  // The generated passphrase is never stored or shown again after this —
  // it only ever exists in plaintext here, on the owner's own machine.
  if (wasGenerated) {
    console.log("Generated passphrase (save this now — it will not be shown again):");
    console.log(`  ${passphrase}`);
    console.log("");
  }

  // Confirmation that the row actually landed in the database — the
  // hash is safe to print (unlike the plaintext passphrase above, a
  // bcrypt hash can't be used to log in on its own) and gives an
  // immediate way to verify the save without opening Supabase.
  console.log("Saved to database:");
  console.log(`  owner_vault row id: ${createdVault.id}`);
  console.log(`  passphrase hash:    ${passphraseHash}`);
  console.log("");

  console.log("Vault created successfully.");
  console.log("Saved a local copy of the passphrase to owner-vault-passphrase.txt — read it, store it somewhere safe, then delete it from disk. Never commit it.");
  console.log("");
  console.log("No QR code was generated (deferred until this project is deployed with its final custom domain — see this file's header). Enter this TOTP secret into your authenticator app manually for now:");
  console.log(`  ${totpSecret}`);
}

main().finally(() => process.exit());